PROXY_USERNAME = "harsha"
PROXY_PASSWORD = "DAnK3YeWE.zEbE4"
PROXY_HOST = "us-ca.proxymesh.com"
PROXY_PORT = "31280"
TWITTER_USERNAME="harsha72539019"
TWITTER_PASSWORD="ozauTk_K-Oa!j7t"
TWITTER_EMAIL="dharsha9949@gmail.com"
MONGODB_URI="mongodb+srv://docsuser:docsuser123@cluster0.lb8gg2f.mongodb.net/"
